import type { SeedBundleV1 } from "@/types/seed";

export const PRODUCTION_SEED_TEMPLATE: SeedBundleV1 = {
  kind: "production",
  sources: [],
  licenses: [],
  reviewers: [],
  chordQualities: [],
  chordQualityIntervals: [],
  chords: [],
  tunings: [],
  tuningCourses: [],
  tuningStrings: [],
  chordShapes: [],
  chordShapePositions: [],
  chordShapeBarres: [],
  rhythms: [],
  rhythmPatterns: [],
  rhythmSteps: [],
  exercises: [],
  exerciseEvents: [],
  assets: [],
  tags: [],
  songs: [],
  songRhythms: [],
  songSources: [],
  songChordIndex: [],
  songArrangements: [],
  songArrangementChords: [],
};
